module.exports = {
  sidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: 'Contributing',
      href: 'https://github.com/Availity/availity-react/blob/master/.github/CONTRIBUTING.md',
    },
    {
      type: 'link',
      label: 'Storybook',
      href: 'https://availity.github.io/availity-react/storybook/',
    },
  ],
};
