module.exports = {
  someSidebar: {
    'React Docs': [
      'intro',
      {
        type: 'link',
        label: 'Contributing',
        href: 'https://github.com/Availity/availity-react/blob/master/.github/CONTRIBUTING.md',
      },
      {
        type: 'link',
        label: 'Storybook', // The label that should be displayed (string).
        href: 'https://availity.github.io/availity-react/storybook/', // The target URL (string).
      },
      {
        type: 'category',
        label: 'Components',
        items: [
          {
            type: 'category',
            label: 'Analytics',
            items: [
              'components/analytics/index',
              'components/analytics/analytics',
              'components/analytics/hook',
            ],
          },
          'components/help',
        ],
      },
      {
        type: 'category',
        label: 'Bootstrap Components',
        items: [
          'bootstrap-components/app-icon',
          'bootstrap-components/app-tiles',
          {
            type: 'category',
            label: 'Authorize',
            items: [
              'bootstrap-components/authorize/index',
              'bootstrap-components/authorize/authorize',
              'bootstrap-components/authorize/useAuthorize',
            ],
          },
          // 'components/authorize',
          'bootstrap-components/avatar',
          'bootstrap-components/button',
          'bootstrap-components/breadcrumbs',
          {
            type: 'category',
            label: 'Change Password',
            items: [
              'bootstrap-components/change-password/index',
              'bootstrap-components/change-password/change-password',
              'bootstrap-components/change-password/change-password-form',
              'bootstrap-components/change-password/use-change-password',
            ],
          },
          {
            type: 'category',
            label: 'Favorites',
            items: [
              'bootstrap-components/favorites/index',
              'bootstrap-components/favorites/favorites',
              'bootstrap-components/favorites/heart',
              'bootstrap-components/favorites/hook',
            ],
          },
          'bootstrap-components/feature',
          {
            type: 'category',
            label: 'Feedback',
            items: [
              'bootstrap-components/feedback/index',
              'bootstrap-components/feedback/feedback',
              'bootstrap-components/feedback/form',
            ],
          },
          {
            type: 'category',
            label: 'Hooks',
            items: [
              'bootstrap-components/hooks/index',
              'bootstrap-components/hooks/use-current-user',
              'bootstrap-components/hooks/use-effect-async',
              'bootstrap-components/hooks/use-mount',
              'bootstrap-components/hooks/use-region',
              'bootstrap-components/hooks/use-timeout',
              'bootstrap-components/hooks/use-toggle',
              'bootstrap-components/hooks/use-permissions',
              'bootstrap-components/hooks/use-organizations',
              'bootstrap-components/hooks/use-providers',
              'bootstrap-components/hooks/use-update-nav',
              'bootstrap-components/hooks/use-window-dimensions',
            ],
          },
          'bootstrap-components/icon',
          {
            type: 'category',
            label: 'JSON Viewer',
            items: [
              'bootstrap-components/json-viewer/index',
              'bootstrap-components/json-viewer/json-viewer',
            ],
          },
          'bootstrap-components/link',
          'bootstrap-components/list-group',
          {
            type: 'category',
            label: 'List Group Item',
            items: [
              'bootstrap-components/list-group-item/index',
              'bootstrap-components/list-group-item/list-group-item',
              'bootstrap-components/list-group-item/list-group-item-status',
            ],
          },
          'bootstrap-components/page-header',
          {
            type: 'category',
            label: 'Pagination',
            items: [
              'bootstrap-components/pagination/index',
              'bootstrap-components/pagination/pagination',
              'bootstrap-components/pagination/controls',
              'bootstrap-components/pagination/content',
              'bootstrap-components/pagination/resource',
              'bootstrap-components/pagination/hook',
              'bootstrap-components/pagination/context',
            ],
          },
          'bootstrap-components/badge',
          'bootstrap-components/progress',
          {
            type: 'category',
            label: 'Spaces',
            items: [
              'bootstrap-components/spaces/index',
              'bootstrap-components/spaces/space',
              'bootstrap-components/spaces/images',
              'bootstrap-components/spaces/disclaimer',
              'bootstrap-components/spaces/agreement',
              'bootstrap-components/spaces/ghost-text',
              'bootstrap-components/spaces/use-spaces',
              'bootstrap-components/spaces/context',
              'bootstrap-components/spaces/use-spaces-context',
            ],
          },
          {
            type: 'category',
            label: 'Step Wizard',
            items: [
              'bootstrap-components/step-wizard/index',
              'bootstrap-components/step-wizard/wizard',
              'bootstrap-components/step-wizard/wizard-step',
            ],
          },
          {
            type: 'category',
            label: 'Table',
            items: [
              'bootstrap-components/table/index',
              'bootstrap-components/table/scrollableContainer',
              'bootstrap-components/table/tableControls',
            ],
          },
          'bootstrap-components/tooltip',
          'bootstrap-components/training-link',
          'bootstrap-components/tree',
          {
            type: 'category',
            label: 'Typography',
            items: [
              'bootstrap-components/typography/index',
              'bootstrap-components/typography/disclaimer',
              'bootstrap-components/typography/agreement',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'Form Components',
        items: [
          'form/index',
          'form/migrating',
          'form/components/checkbox-group',
          'form/components/checkbox',
          'form/components/feedback',
          'form/components/field',
          'form/components/form-group',
          'form/components/form',
          'form/components/input',
          'form/components/label',
          'form/components/help-icon',
          'form/components/radio-group',
          'form/components/radio',
          {
            type: 'category',
            label: 'Date',
            items: [
              'form/date/index',
              'form/date/components/date',
              'form/date/components/date-field',
              'form/date/components/date-range',
              'form/date/components/date-range-field',
            ],
          },
          {
            type: 'category',
            label: 'Phone',
            items: [
              'form/phone/index',
              'form/phone/components/phone',
              'form/phone/components/validate-phone',
            ],
          },
          {
            type: 'category',
            label: 'Select',
            items: [
              'form/select/index',
              'form/select/components/select',
              'form/select/components/select-field',
              'form/select/components/resource-select',
              'form/select/components/region-select',
              'form/select/components/organization-select',
              'form/select/components/payer-select',
            ],
          },
          {
            type: 'category',
            label: 'Upload',
            items: [
              'form/upload/index',
              'form/upload/upload',
              'form/upload/file-picker',
              'form/upload/file-picker-btn',
              'form/upload/upload-progress-bar',
            ],
          },
        ],
      },
    ],
  },
};
