root: true
extends: availity/browser
rules:
  import/extensions: 0
  react/destructuring-assignment: 0
  react/forbid-foreign-prop-types: 0
  react/no-access-state-in-setstate: 0
  guard-for-in: 0
  no-restricted-syntax: 0
  react/prefer-stateless-function: 0
  unicorn/prefer-array-find: 0
  unicorn/no-abusive-eslint-disable: 0
  unicorn/no-lonely-if: 0
  unicorn/no-array-for-each: 0
  no-restricted-exports: 0
  jest/no-deprecated-functions: 0
  jest/no-conditional-expect: 0
  jest/no-commented-out-tests: 0
globals:
  vi: false
settings:
  jest:
    version: 30
