name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Commit Message
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
