# This workflow will do a clean install of node dependencies, build the source code, and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# If adding a step that requires SECRETS or GITHUB WRITE PERMISSIONS be sure to have dependabot skip it.
# > if: ${{ github.actor != 'dependabot[bot]' }}

name: Pull Request Build

on:
  pull_request:
    branches: [master]

jobs:
  # This job will:
  #   * deploy a draft every time there is a pull request created or synchronized that is not on master branch
  #   * comment on that pull request with the deploy URL
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [22, 24]

    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1
        with:
          main-branch-name: 'master'

      - name: Set Node Version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      # - name: Artifactory Check
      #   run: yarn check:registry

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Restore Nx Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}-

      - name: Build
        run: yarn build:components

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn nx affected --target=lint

      - name: Unit Test
        run: yarn test:ci

      - name: Version Bump Dry Run
        run: yarn version:dry-run

      - name: Build Docs
        if: ${{ matrix.node == 24 }}
        run: yarn build:docs

      - name: Build Storybook
        if: ${{ matrix.node == 24 }}
        run: yarn build:storybook
